
description: "A site for everything interesting!"

header_pages:
  - index.md
  - about.md
  - contact.md

style: dark

footer: 'yep.'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
